language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install --no-interaction

script:
  - composer lint
  - composer test

